In [6]:
## Extract image dimensions and add to CSV

from PIL import Image
import os
import pandas as pd

# Read in CSV
input_path = '/Users/caraappel/Documents/CV4E/oregon_critters/metadata_labels/both_split.csv' #change here
dataframe = pd.read_csv(input_path)

In [7]:
dataframe['full_name'].values

array(['/Users/caraappel/Documents/CV4E/data/COA_2019/hailey.hester-COA2019_Coyote/images/10022-4__2019-07-30__08-43-18(1)_hx.JPG',
       '/Users/caraappel/Documents/CV4E/data/COA_2019/hailey.hester-COA2019_Coyote/images/10022-4__2019-07-30__08-43-19(2)_hx.JPG',
       '/Users/caraappel/Documents/CV4E/data/COA_2019/hailey.hester-COA2019_Coyote/images/10022-4__2019-07-30__08-43-19(3)_hx.JPG',
       ...,
       '/Users/caraappel/Documents/CV4E/data/COA_2020/hailey.hester-COA_2020_DouglasSquirrel_HH/images/Drive_03_06220095_ie.JPG',
       '/Users/caraappel/Documents/CV4E/data/COA_2020/hailey.hester-COA_2020_VariedThrush_HH/images/Drive_03_06260097_iu.JPG',
       '/Users/caraappel/Documents/CV4E/data/COA_2020/hailey.hester-COA_2020_VariedThrush_HH/images/Drive_03_06260098_iu.JPG'],
      dtype=object)

In [8]:
# Define function to get image dimensions
def get_image_dimensions(filename):
    with Image.open(filename) as img:
        return img.size

In [9]:
# Create lists to store dim
width_output = []
height_output = []

# Extract dimensions
for image in dataframe['full_name'].values:
    width, height = get_image_dimensions(image)
    width_output.append(width)
    height_output.append(height)
    
# Append to CSV
dataframe['img_width'] = width_output
dataframe['img_height'] = height_output

dataframe.head()

,Unnamed: 0,V1,full_path_orig,LID,CName,X,Y,W,H,IName,...,day_night,year,remove,full_path,stn,sequence_id,group,cam_type_2,img_width,img_height
0,1,1,data/COA_2019/hailey.hester-COA2019_Coyote/ima...,1,Coyote,2.487805,967.756098,440.341463,681.658537,10022-4__2019-07-30__08-43-18(1).JPG,...,night,2019,keep,data/COA_2019/hailey.hester-COA2019_Coyote/ima...,10022-4-T,103,train,T,3264,2448
1,2,2,data/COA_2019/hailey.hester-COA2019_Coyote/ima...,2,Coyote,2.487805,853.317073,440.341463,728.926829,10022-4__2019-07-30__08-43-19(2).JPG,...,night,2019,keep,data/COA_2019/hailey.hester-COA2019_Coyote/ima...,10022-4-T,103,train,T,3264,2448
2,3,3,data/COA_2019/hailey.hester-COA2019_Coyote/ima...,3,Coyote,4.975610,816.000000,420.439024,738.878049,10022-4__2019-07-30__08-43-19(3).JPG,...,night,2019,keep,data/COA_2019/hailey.hester-COA2019_Coyote/ima...,10022-4-T,103,train,T,3264,2448
3,4,4,data/COA_2019/COA2019_Bat/images/10316-5__2019...,4,Bat,1414.630021,1792.900518,824.016913,425.915281,10316-5__2019-08-05__04-43-55(1).JPG,...,night,2019,keep,data/COA_2019/COA2019_Bat/images/10316-5__2019...,10316-5-T,2093,test,T,3840,2880
4,5,5,data/COA_2019/COA2019_Bat/images/10831-1__2019...,15,RooseveltElk,294.291755,1784.787846,1359.830867,965.407971,10831-1__2019-08-07__01-08-48(7).JPG,...,night,2019,keep,data/COA_2019/COA2019_Bat/images/10831-1__2019...,10831-1-T,5462,test,T,3840,2880

In [10]:
# Save new CSV

output_path = input_path.replace('.csv', '_dim.csv')
dataframe.to_csv(output_path)

print('saved file' + output_path)

saved file/Users/caraappel/Documents/CV4E/oregon_critters/metadata_labels/both_split_dim.csv